//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estate()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int ID { get; set; }
        public int EstateAgentID { get; set; }
        public string Address { get; set; }
        public decimal Price { get; set; }
        public bool IsSale { get; set; }
        public bool IsRent { get; set; }
        public decimal M2 { get; set; }
        public int EstateCategoryID { get; set; }
        public int Floor { get; set; }
        public bool IsFurnished { get; set; }
        public int TotalFloor { get; set; }
        public int RoomID { get; set; }
    
        public virtual EstateAgent EstateAgent { get; set; }
        public virtual EstateCategory EstateCategory { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
